### ISSUE TITLE
Open dropdown to top if not enough space available to bottom

### ISSUE THREAD

**Issue by Kathara** [FrontendMetis/nativejs-select#18]
When clicking on a rendered nativejs-select the dropdown always opens to the bottom of the container. But if the nativejs-select is at the bottom of the page (e.g. in a `position:fixed` container) the dropdown and its contents are barely visible. Could this be optimized?

**Comment by vrg-success** [comment]
Hi, I think that I will do the feature

**Comment by Kathara** [comment]
Very nice, thank you :-) 👍
